site_name: Optics
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: optic-light
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: optic-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
      - content.code.copy

extra_css:
  - stylesheets/extra.css

  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true

  - pymdownx.superfences
